const TOKEN_VARIABLE_NAME = 'mapToken';
const TOKEN_HEADER_KEY = 'Authorization';
const ROLE_ADMIN = 'ADMIN';
const ROLE_USER = 'USER';

// color
const PLACE_NORMAL_COLOR = '#000000bd'
const PLACE_SELECTED_COLOR = '#236292'
const PLACE_MARKED_COLOR = '#c60808'
const REGION_NORMAL_COLOR = '#B0C6D8'
const REGION_MARKED_25_COLOR = '#87b5da'
const REGION_MARKED_50_COLOR = '#6765e5'
const REGION_MARKED_75_COLOR = '#945be1'
const REGION_MARKED_100_COLOR = '#882f61'

export const constant = {
   TOKEN_VARIABLE_NAME
   , TOKEN_HEADER_KEY
   , ROLE_ADMIN
   , ROLE_USER
   , PLACE_NORMAL_COLOR
   , PLACE_SELECTED_COLOR
   , PLACE_MARKED_COLOR
   , REGION_NORMAL_COLOR
   , REGION_MARKED_25_COLOR
   , REGION_MARKED_50_COLOR
   , REGION_MARKED_75_COLOR
   , REGION_MARKED_100_COLOR
}