const TOKEN_VARIABLE_NAME = 'mapToken';
const TOKEN_HEADER_KEY = 'Authorization';
const ROLE_ADMIN = 'ADMIN';
const ROLE_USER = 'USER';

// color
const PLACE_NORMAL_COLOR = '#000000bd'
const PLACE_SELECTED_COLOR = '#236292'
const PLACE_MARKED_COLOR = '#c60808'
const REGION_NORMAL_COLOR = '#CCD8DE'
const REGION_MARKED_30_COLOR = '#5BB7D4'
const REGION_MARKED_80_COLOR = '#016699'
const REGION_MARKED_100_COLOR = '#00CE7D'

// for TOAST
const TOAST_TYPE_ERROR = 'ERROR';
const TOAST_TYPE_SUCCESS = 'SUCCESS';
const TOAST_TYPE_INFO = 'INFO';

export const constant = {
   TOKEN_VARIABLE_NAME
   , TOKEN_HEADER_KEY
   , ROLE_ADMIN
   , ROLE_USER
   , PLACE_NORMAL_COLOR
   , PLACE_SELECTED_COLOR
   , PLACE_MARKED_COLOR
   , REGION_NORMAL_COLOR
   , REGION_MARKED_30_COLOR
   , REGION_MARKED_80_COLOR
   , REGION_MARKED_100_COLOR

   , TOAST_TYPE_ERROR
   , TOAST_TYPE_SUCCESS
   , TOAST_TYPE_INFO
}