const TOKEN_VARIABLE_NAME = 'mapToken';
const TOKEN_HEADER_KEY = 'Authorization';
const ROLE_ADMIN = 'ADMIN';
const ROLE_USER = 'USER';

// color
const PLACE_NORMAL_COLOR = '#000000bd'
const PLACE_SELECTED_COLOR = '#236292'
const PLACE_MARKED_COLOR = '#c60808'
const REGION_NORMAL_COLOR = '#ECEDEF'
const REGION_MARKED_30_COLOR = '#5CE1C0'
const REGION_MARKED_80_COLOR = '#FFD235'
const REGION_MARKED_100_COLOR = '#FF6F61'

export const constant = {
   TOKEN_VARIABLE_NAME
   , TOKEN_HEADER_KEY
   , ROLE_ADMIN
   , ROLE_USER
   , PLACE_NORMAL_COLOR
   , PLACE_SELECTED_COLOR
   , PLACE_MARKED_COLOR
   , REGION_NORMAL_COLOR
   , REGION_MARKED_30_COLOR
   , REGION_MARKED_80_COLOR
   , REGION_MARKED_100_COLOR
}